#!/bin/bash
# Quick script to move existing processes to background

echo "=========================================="
echo "Current Status:"
echo "=========================================="
echo ""
echo "✓ Dashboard URL: https://1b0afc0da283.ngrok-free.app/forex_macd_dashboard.html"
echo ""
echo "Your services are currently running in terminal pts/4"
echo ""
echo "IMPORTANT: To keep these running when you close your laptop:"
echo ""
echo "Option 1 - Keep current processes (simplest):"
echo "  - Just keep the terminal open (minimize it)"
echo "  - Don't close the terminal or laptop will suspend processes"
echo ""
echo "Option 2 - Move to screen session (recommended):"
echo "  1. Install screen: sudo apt-get install screen"
echo "  2. Stop current processes: pkill -f 'serve_forex_macd|forex_macd_strategy|ngrok'"
echo "  3. Start in screen: ./run_with_internet.sh start"
echo ""
echo "Option 3 - Use nohup (current processes):"
echo "  - Your processes are already running"
echo "  - They'll continue as long as the terminal stays open"
echo ""
echo "=========================================="
echo "Quick Commands:"
echo "=========================================="
echo "Get URL again: curl -s http://localhost:4040/api/tunnels | grep -o '\"public_url\":\"https://[^\"]*' | head -1 | cut -d'\"' -f4"
echo "Check status:  ps aux | grep -E 'ngrok|serve_forex_macd|forex_macd_strategy' | grep -v grep"
echo "=========================================="
